version: '3'
services:
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: pythonreact
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./dockerForMongoDB/mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
    depends_on:
      - db

  frontend:
    build: ./dockerForFrontend
    ports:
      - "3000:3000"

  backend:
    build:  ./dockerForBackend
    command: ["flask", "run", "--host=0.0.0.0"]
    ports:
      - "5000:5000"
  skin:
    build: ./dockerForTensorflow
    ports:
      - "5004:5000"
    depends_on:
        - backend


volumes:
  mongodata:
    driver: local
